[program:server-monitor]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/server_monitoring/artisan monitor:run
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/server_monitoring/storage/logs/monitor-daemon.log
stopwaitsecs=3600
